### ISSUE TITLE
Terminal Scroll History Issue

### ISSUE THREAD

**Issue by kkiernan** [Wramberg/TerminalView#28] opened 2017-07-12 18:17 UTC
Not sure if this is a bug or a configuration issue on my part. Any help is appreciated. I installed the plugin and added the example key binding. Works wonderfully, but I am unable scroll back to view any history. I can only see what is visible in the window, and once output goes above the viewable area, I can no longer scroll back to it. Any thoughts?

**OS**: macOS Sierra 10.12.5
**ST3 Version**: Stable Channel, Build 3126
**Bash Version**: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
**Arguments**: Just using the example binding from the README:

```
[
    { "keys": ["ctrl+alt+t"], "command": "terminal_view_open" }
]
```

**Env**:

```
TERM=linux                                                                                                  
SHELL=/bin/bash                                                                                             
TMPDIR=/var/folders/70/9xkw9vyd1s3cs2znrc0kb_mc0000gn/T/                                                    
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.N3TUYuh4NF/Render                                 
USER=kelly                                                                                                  
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.tJWd1ElSXE/Listeners                                           
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0                                                                       
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/kelly/.composer/vendor/bin:/Users/kelly/pear/bin                                                                                           
PWD=/Users/kelly/Documents/Code/my_project                                             
XPC_FLAGS=0x0                                                                                               
XPC_SERVICE_NAME=0                                                                                          
SHLVL=1                                                                                                     
HOME=/Users/kelly                                                                                           
LOGNAME=kelly                                                                                               
_=/usr/bin/env
```

**Comment by Wramberg** [comment] 2017-07-12 20:41
Have to checked if your user keymap shadows the scrolling keybindings ?
You can try inserting the following in your user keymap and see if it works.

```
    {"keys": ["shift+pageup"], "command": "terminal_view_scroll", "args": {"forward": false}, "context": [{"key": "setting.terminal_view"}]},
    {"keys": ["shift+pagedown"], "command": "terminal_view_scroll", "args": {"forward": true}, "context": [{"key": "setting.terminal_view"}]},
```

**Comment by kkiernan** [comment] 2017-07-13 14:25
Yep that did it. Thank you so much! @Wramberg

**Comment by megadr01d** [comment] 2017-07-18 10:26
@Wramberg 

In the [keybindings](https://github.com/Wramberg/TerminalView#keybindings) section, there's an entry for

<kbd>alt</kbd> + <kbd>mouse wheel up</kbd> / <kbd>mouse wheel down</kbd> - Scroll back/forward in terminal history

but doesn't seem to work on OS X. I'm using the MacBook Pro's built-in trackpad, not a mouse. Does it work on your system (linux?) or it's not implemented?

<kbd>shift</kbd> + <kbd>pageup</kbd> / <kbd>pagedown</kbd> work correctly.

Let me know if I should create a new issue for this.

**Comment by Wramberg** [comment] 2017-07-22 16:08
Hi @megadr01d alt+scroll wheel works fine on Linux. Unfortunately I do not have a macbook to test on. Maybe @rwols or @randy3k can tell us whether it works on macOS (mouse wheel and/or trackpad scroll).

**Comment by randy3k** [comment] 2017-07-22 16:12
It is not working with trackpad on my iMac and MacBook Pro. It seems that the command is never got executed. Not sure about mouse though.

**Comment by Wramberg** [comment] 2017-07-22 16:20
Thanks @randy3k thats not intended. I wonder if ST3 has another name for trackpad scroll ? I only tested it using a mouse. Could you try testing it with a mouse @megadr01d ?

**Comment by megadr01d** [comment] 2017-07-22 16:27
Thanks for the confirmation, @randy3k.

@Wramberg Unfortunately I don't own a mouse but the trackpad scrolling works on a standard view.
When I get home, I'll try [setting a different modifier](https://github.com/Wramberg/TerminalView/blob/master/Default.sublime-mousemap) and use PackageResourceViewer to dissect ST's internal `.sublime-mousemap` file.

**Comment by randy3k** [comment] 2017-07-22 16:29
Although TerminalView scroll is a very different story from the regular view scrolling.

**Comment by Wramberg** [comment] 2017-07-22 16:31
Indeed TerminalView scrolling is very different from ST3 view scrolling. Regardless please report back your findings @megadr01d  and feel free to open an issue if you figure out how to fix it :-)

**Comment by megadr01d** [comment] 2017-07-22 16:38
> Although TerminalView scrolling is a very different story from the regular view scrolling.

I know it's using pyte, but the same applies to Linux where it works correctly.
Thanks again guys, I'll report back.

**Comment by rwols** [comment] 2017-07-22 20:15
Can confirm that <kbd>alt</kbd>+<kbd>trackpad scroll</kbd> doesn't do anything.

**Comment by kkiernan** [comment] 2017-07-23 02:18
Just confirming that the mouse scroll bindings do not work with the mouse on OS X. This is why I was confused at first and opened the issue originally. I tried a few different bindings but couldn't get anything to work unfortunately.

**Comment by megadr01d** [comment] 2017-07-23 14:32
Different modifiers don't work but I found it's somehow an OS X limitation.
I unzipped ST's `Default.sublime-package` and found the following:

```json
Default (Linux).sublime-mousemap
...
// Change font size with ctrl+scroll wheel
{ "button": "scroll_down", "modifiers": ["ctrl"], "command": "decrease_font_size" },
{ "button": "scroll_up", "modifiers": ["ctrl"], "command": "increase_font_size" },
...
```

```json
Default (Windows).sublime-mousemap
...
// Switch files by holding down button 2, and using the scroll wheel
{ "button": "scroll_down", "modifiers": ["button2"], "command": "next_view" },
{ "button": "scroll_up", "modifiers": ["button2"], "command": "prev_view" },

// Change font size with ctrl+scroll wheel
{ "button": "scroll_down", "modifiers": ["ctrl"], "command": "decrease_font_size" },
{ "button": "scroll_up", "modifiers": ["ctrl"], "command": "increase_font_size" },
...
```

For some reason, `Default (OSX).sublime-mousemap` doesn't contain the `scroll_up` or `scroll_down` keys.

Also tried

```json
[
    { "button": "scroll_up", "modifiers": ["alt"], "command": "increase_font_size" },
    { "button": "scroll_down", "modifiers": ["alt"], "command": "decrease_font_size" }
]
```

and confirmed that it doesn't work for changing font size either, so my guess is that this is an issue with ST and not TerminalView.

**Comment by Wramberg** [comment] 2017-07-23 15:30
Thanks for the update @megadr01d - I guess there is nothing to be done (atleast at the moment) unfortunately ?

**Comment by megadr01d** [comment] 2017-07-23 17:49
@Wramberg Yeah. Scrolling with the keyboard works fine so, no major problem. I added this to my scratchpad  to post on Sublime Text's Issues repo, later on, so @kkiernan, you can close this one again, for now.

**Comment by Wramberg** [comment] 2017-07-23 19:32
Thanks @megadr01d I have added a note in the readme about this so we can close this for now until something changes with ST3.

**Closed by Wramberg** 2017-07-23 19:32 UTC

**Comment by megadr01d** [comment] 2017-07-27 16:21
Reference issue on SublimeTextIssues official repo, in case you wanna link in the readme or just keep an eye on it.

https://github.com/SublimeTextIssues/Core/issues/1838

**Comment by quantumds** [comment] 2018-04-19 17:43
Any updates on this issue? ST3 + Anaconda is a fantastic setting, ntl I must always come back to Anaconda Spyder due to this issue. Thanks!

**Comment by Wramberg** [comment] 2018-04-20 07:06
Until https://github.com/SublimeTextIssues/Core/issues/1838 gets resolved I'm afraid there's not much to do.

**Comment by quantumds** [comment] 2018-11-24 11:53
Can confirm now that: Alt + using scroll wheel with generic mouse (not trackpad) in new MacOS Mojave 10.14.1 works and you are able to see all the historic of your code lines in the terminal. Bit uncomfortable but at least it is an alternative.
