### ISSUE TITLE
Some subprocesses are not closed when Sublime Text is closed

### ISSUE THREAD

**Issue by randy3k** [Wramberg/TerminalView#33] opened 2017-07-13 05:25 UTC
Say for example I am running a Julia interpreter in TerminalView.

Check from Terminal.
```bash
(randyimac)-~$ ps aux | grep julia
Randy            81312   0.0  0.0  2432804   1976 s062  S+    1:20AM   0:00.00 grep --color=auto julia
Randy            81309   0.0  1.8  2924696 153312   ??  S     1:20AM   0:00.41 julia
```

Close sublime text completely and check again.
```
(randyimac)-~$ ps aux | grep julia
Randy            81309 100.0  2.2  2924696 184280   ??  R     1:20AM   0:02.08 julia
Randy            81320   0.0  0.0  2433828   1888 s062  R+    1:21AM   0:00.00 grep --color=auto julia
```

The process 81320 is not closed automatically. 

Oddly, it always happens for Julia console. R or python consoles do **sometimes** close.

**Comment by randy3k** [comment] 2017-07-13 06:54
I was using zsh, I guess it may be the reason.

**Comment by Wramberg** [comment] 2017-07-13 07:33
It seems like a pretty serious issue so I'll look into this when I get the time - just to be sure.

**Comment by Wramberg** [comment] 2017-07-23 10:34
Cant seem to replicate this on Linux so I'll close it. If anyone finds a way to reproduce it feel free to reopen so we can investigate further. For now I'll write it off as zsh not shutting down gracefully or something when it does not have bash as parrent process.

**Closed by Wramberg** 2017-07-23 10:34 UTC

**Comment by randy3k** [comment] 2017-09-02 03:26
I could still reproduce it when running a heavy command in the terminal.

Step:

- open shell (bash / zsh)
- run a very heavy command, for my case, I am using Julia and compile a package.
- close sublime text completely
- from a regular terminal, I can still see the process

```
(randyimac)-~$ ps aux | grep julia
Randy            75676 100.0  2.6  2950452 221716   ??  Rs   11:23PM   0:06.27 /Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes -O0 --output-ji /Users/Randy/.julia/lib/v0.6/BandedMatrices.ji --output-incremental=yes --startup-file=no --history-file=no --color=yes --eval while !eof(STDIN)\012    eval(Main, deserialize(STDIN))\012end\012
``

And interestingly, `kill 75676` also doesn't kill the process. To kill it, I need to execute `kill -9 75676 `

**Comment by randy3k** [comment] 2017-09-02 03:40
ai....it may an issue of Julia itself....I can reproduce the same thing on a regular terminal.

Sorry for the noise.

**Comment by Wramberg** [comment] 2017-09-03 13:12
Glad you found the cause - very glad its not with TerminalView ;-)
