### ISSUE TITLE
Clearing screen using `clear` does not scroll the view to the top

### ISSUE THREAD

**Issue by aziz** [Wramberg/TerminalView#14] opened 2017-06-13 22:09 UTC
Additionally clearing screen just wipe out all the history. 
How about changing this behavior so that clearing just scrolls the prompt to the top of the screen. I know this is possible using the ST API

**Comment by Wramberg** [comment] 2017-06-14 05:17
I am looking into scrolling as a feature on another branch - its not as easy as just scrolling the view since i am using a terminal emulator that only supports screens of chars. What happens you "clear" the temrinal ? I assume you get an empty prompt at the top of the screen. If this is the case the plugin is working as intended right now.

**Comment by Wramberg** [comment] 2017-06-16 06:00
Closing this as I don't see it as an issue. With no scrolling this is working as intended. Even when scrolling is implemented Pyte still clears the screen when clear is called.

**Closed by Wramberg** 2017-06-16 06:00 UTC

**Comment by randy3k** [comment] 2017-07-11 20:06
`Ctrl-l` to clear screen doesn't work. Is it related to this?

**Comment by Wramberg** [comment] 2017-07-11 20:12
Ctrl-l should clear the screen in the latest version. Ill have a look at this tomorrow.

**Comment by randy3k** [comment] 2017-07-11 20:13
Thanks for the headup. I am on the master branch but it is not working.

**Comment by Wramberg** [comment] 2017-07-12 05:47
If I have a screen like this in my terminal view

```
jw@jw-VirtualBox:~/TerminalView$                                                                                    
jw@jw-VirtualBox:~/TerminalView$                                                                                    
jw@jw-VirtualBox:~/TerminalView$ 1                                                                                  
1: command not found                                                                                                
jw@jw-VirtualBox:~/TerminalView$ 2                                                                                  
2: command not found                                                                                                
jw@jw-VirtualBox:~/TerminalView$ 3                                                                                  
3: command not found                                                                                                
jw@jw-VirtualBox:~/TerminalView$ 4                                                                                  
4: command not found                                                                                                
jw@jw-VirtualBox:~/TerminalView$ 5                                                                                  
5: command not found                                                                                                
jw@jw-VirtualBox:~/TerminalView$ 6                                                                                  
6: command not found                                                                                                
jw@jw-VirtualBox:~/TerminalView$ 7                                                                                  
7: command not found                                                                                                
jw@jw-VirtualBox:~/TerminalView$ 
```

and hit ctrl-l then screen shows

```
jw@jw-VirtualBox:~/TerminalView$
















```

As expected. If ctrl-c does not work for you maybe your TERM variable is overridden somewhere ? It needs to be "linux" for TerminalView to work properly.

**Comment by randy3k** [comment] 2017-07-12 06:13
Sorry for the noise...it is because of a key bind conflict...
